name: CI
on: 
  push:
  pull_request:
jobs:
  nblint:
    name: Lint Notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cleanlab/nblint-action
        with:
          directory: "cleanlab/"
        