name: CI
on: [push]
jobs:
  badges:
    name: Colab Badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: all
          target_branch: master
          target_repository: huiwengoh/test_ci
          update: true
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add Colab badge
  nblint:
    name: Lint Notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: nblint
        run: ./.ci/nblint.py . 
        